A fix if the usb_external is bigger than internal_storage
eupnea-linux/postinstall-scripts pull request #1
Opened 2022-10-21 15:39 UTC by Emprario

This fix is in the case which the usb_external is bigger than internal_storage (so dd return an error). So I use rsync (and exclude some directory). By the way, it should be faster.

2022-10-21 19:51 UTC, Apacelus reviewed
Does rsync preserve **ALL** all permissions of the files?

2022-10-21 20:04 UTC, Apacelus requested changes
Fedora does not login anymore after installing with this script -> permissions are not preserved

2022-10-22 13:07 UTC, Emprario commented
The -a flag should preserve all permissions, owners and groups. Are you sure it's not an error with something else ? Anyway, I modify the script by adding some flags, maybe it will work now. Could you retry ?

2022-10-22 22:54 UTC, Apacelus commented
Alright, seems to work now. Thank you for the pr.

2022-10-22 22:54 UTC, merged